[package]
name = "chronicle"
version = "0.2.2"
edition = "2024"
authors = ["Alvaro Tolentino <alvarotolentinou@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[dependencies]
git2 = "0.20.1"
clap = { version = "4.0", features = ["derive"] }
regex = "1.5"
chrono = "0.4"
thiserror = "2.0.12"
